CREATE TABLE DUMMY_TABLE
(
  DUMMY_COLUMN VARCHAR2(10 CHAR)
);

ALTER TABLE DUMMY_TABLE
  ADD (
  CONSTRAINT DUMMY_TABLE_PK
  PRIMARY KEY
    (DUMMY_COLUMN)
  ENABLE VALIDATE);

INSERT INTO DUMMY_TABLE (DUMMY_COLUMN) VALUES ('Dummy data');

COMMIT;